version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: org.springframework:spring-core
        versions: "> 6.2.0.Final"
